# Generated by Django 3.1.7 on 2022-04-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pictures',
            field=models.ImageField(blank=True, default='userprofile/default.jpg', upload_to='userprofile'),
        ),
    ]
